[package]
name = "enricher"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["json"] }
anyhow = { workspace = true }